### ISSUE TITLE
feat: Websites monorepo

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/adonyssantos#2]
### TODO

- [ ] Initialize mono repo config
- [ ] Mege with `adonyssantos/portfolio`
- [ ] Mege with `adonyssantos/adonyssantos.github.io`
